<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="container">
    <form action = "/send" method="POST" >
  <div class="form-group">
    <label >Your email</label>
    <input name = "username" type="email" class="form-control" >
  </div>
  <div class="form-group">
    <label >Password</label>
    <input name = "password" type="password" class="form-control" >
  </div>
  <div class="form-group">
    <label >To:</label>
    <input name = "to" type="email" class="form-control" >
  </div>
  <div class="form-group">
    <label >Text:</label>
<textarea name = "text" class="form-control" rows="3"></textarea>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>

  </body>
</html>
